import { useRef } from 'react';
import { Maximize, Video, Play, Square } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useCommand } from './store';
import { Badge } from './shared';
import { monitoringApi } from '@/lib/monitoring-api';

export function CameraSelector() { const { cameras, selectedCamera, setSelectedCamera } = useCommand(); return <select aria-label="Select camera" value={selectedCamera} onChange={e => setSelectedCamera(e.target.value)}><option value="">Select a camera</option>{cameras.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select>; }
export function Feed({ large = false }: { large?: boolean }) {
 const { cameras, selectedCamera, monitoring, notify } = useCommand();
 const container = useRef<HTMLDivElement>(null); const camera = cameras.find(c => c.id === selectedCamera);
 const fullscreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await container.current?.requestFullscreen(); } catch { notify('Fullscreen is unavailable.'); } };
 return <div className={`feed-container ${large ? 'feed-large' : ''}`} ref={container}><div className="feed-top"><div className="flex items-center gap-2"><Video size={16} /><strong>{camera?.name ?? 'No camera selected'}</strong><Badge tone={monitoring === 'Running' ? 'normal' : 'muted'}>{monitoring === 'Running' ? 'MONITORING' : 'STANDBY'}</Badge></div><Button size="icon" variant="ghost" title="Fullscreen" aria-label="Fullscreen" onClick={fullscreen}><Maximize /></Button></div><div className="camera-image feed-placeholder"><div className="feed-state"><Video size={30} /><h3>{monitoring === 'Running' ? 'AI Monitoring Active' : 'Monitoring is not active'}</h3><p>{monitoring === 'Running' ? 'Camera process running · Waiting for browser video stream' : 'Start monitoring to run the camera process'}</p></div></div><div className="feed-bottom"><span>{camera ? `${camera.sourceType} · ${camera.location}` : 'No camera selected'}</span><span>{monitoring === 'Running' ? 'Camera process running' : 'No active process'}</span></div></div>;
}
export function MonitoringControls() { const { monitoring, setMonitoring, cameras, setCameras, selectedCamera, notify, refreshCameras, setSelectedCamera, setTelemetry } = useCommand(); const camera = cameras.find(c => c.id === selectedCamera); const start = async () => { if (!camera) return; try { await monitoringApi.start(camera.id); setCameras(previous => previous.map(item => item.id === camera.id ? { ...item, status: 'Online' } : item)); setSelectedCamera(camera.id); setMonitoring('Running'); notify('Monitoring active'); void refreshCameras(); } catch (e) { notify(e instanceof Error ? e.message : 'Unable to start monitoring.'); } }; const stop = async () => { if (!camera) return; try { await monitoringApi.stop(camera.id); setCameras(previous => previous.map(item => item.id === camera.id ? { ...item, status: 'Standby' } : item)); setMonitoring('Stopped'); setTelemetry(null); notify('Monitoring stopped'); void refreshCameras(); } catch (e) { notify(e instanceof Error ? e.message : 'Unable to stop monitoring.'); } };
 return <div className="flex flex-wrap gap-2"><Button disabled={!camera || monitoring === 'Running'} onClick={() => void start()}><Play />Start Monitoring</Button><Button variant="outline" disabled={!camera || monitoring !== 'Running'} onClick={() => void stop()}><Square />Stop</Button></div>; }
