import type { ReactNode } from 'react';
import { X, ArrowUpRight, Camera, Users, BellRing, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useCommand } from './store';
export function Badge({ children, tone = 'muted' }: { children: ReactNode; tone?: string }) { return <span className={`status-badge tone-${tone}`}><span className="status-dot" />{children}</span>; }
export function PageHeading({ eyebrow = 'SECURITY OPERATIONS', title, subtitle, children }: { eyebrow?: string; title: string; subtitle: string; children?: ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div><div className="heading-actions">{children}</div></div>; }
export function Panel({ title, extra, children, className = '' }: { title: string; extra?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}><header className="panel-heading"><h2>{title}</h2>{extra}</header>{children}</section>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" onClick={onClose}><section role="dialog" aria-modal="true" aria-label={title} className="modal" onClick={e => e.stopPropagation()}><header className="panel-heading"><h2>{title}</h2><Button variant="ghost" size="icon" aria-label="Close dialog" onClick={onClose}><X /></Button></header><div className="modal-body">{children}</div></section></div>; }
export function Stats() { const { cameras, telemetry } = useCommand(); const items = [{label:'ACTIVE CAMERAS',value:String(cameras.filter(c=>c.status==='Online').length),caption:'From Flask camera registry',icon:Camera},{label:'TOTAL DETECTED PEOPLE',value:telemetry ? String(telemetry.total_people) : '--',caption:'Current camera telemetry',icon:Users},{label:'ACTIVE ALERTS',value:'--',caption:'Alerts API not connected',icon:BellRing},{label:'CRITICAL ZONES',value:telemetry ? String(Object.values(telemetry.zones).filter(z=>z.status.toUpperCase()==='CRITICAL').length) : '--',caption:'Current camera telemetry',icon:ShieldAlert}]; return <div className="stats-grid">{items.map((item,i)=><article className="stat-card" key={item.label}><div className="stat-top"><span>{item.label}</span><item.icon size={19}/></div><div className="stat-value">{item.value}</div><div className="stat-bottom"><span>{item.caption}</span><ArrowUpRight size={15}/></div></article>)}</div>; }
export function ZoneCards() { const { telemetry } = useCommand(); if (!telemetry) return <div className="empty-state">No live monitoring data available</div>; return <div className="zone-cards">{Object.entries(telemetry.zones).map(([name,z])=><article className="zone-card" key={name}><div className="flex items-center justify-between"><h3>{name}</h3><Badge tone={z.status.toLowerCase()}>{z.status}</Badge></div><div className="zone-numbers"><strong>{z.people}<span> / {z.capacity}</span></strong><span>{z.occupancy}% <small>occupancy</small></span></div><progress max={100} value={Math.min(100,z.occupancy)}/></article>)}</div>; }
